name: Docker Compose CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  docker-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images from docker-compose
        run: docker compose build

      - name: List images
        run: docker images

      - name: Create & start containers (for testing)
        run: docker compose up -d

      - name: List running containers
        run: docker ps -a

      - name: Wait for 6 minutes
        run: sleep 360

      - name: Logs for frontend
        run: docker compose logs frontend 

      - name: Logs for backend
        run: docker compose logs backend
